### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by X901** [xxxAIRINxxx/MusicPlayerTransition#18]
Hi , 
I need to use this library but it make me confuse , I can't find enough information about how to use it , like how others libraries does in README.md file .
 README.md doesn't contents enough information. Could you please update it ?

**Comment by xxxAIRINxxx** [comment]
Hi 😄 
This is not intended for libraries.
It is an example of how to use ARNTransitionAnimator.

**Comment by yarodevuci** [comment]
@X901 Just follow the example
