### ISSUE TITLE
UITransitionView not removed

### ISSUE THREAD

**Issue by AppinessVashum** [xxxAIRINxxx/MusicPlayerTransition#28]
While playing around with the demo app, there is a very strange bug where UITransitionView was not removed and it freezes all user action:
Steps to reproduce
1. swipe up and down or swipe up MiniPlayerView and release finger without letting to present ModalViewController
2. Continue step 1 for n times until the screen is freeze

Here is the print log before freezing the app

ViewController viewWillAppear
ModalViewController viewWillDisappear
ModalViewController viewWillAppear
MusicPlayerTransitionAnimation willAnimation(_ transitionType: TransitionType, containerView: UIView)
ViewController viewWillAppear
![screen shot 2018-08-01 at 6 07 50 pm](https://user-images.githubusercontent.com/32291381/43523750-054fba4c-95bb-11e8-93cf-e82ff92735c8.png)

**Comment by kipYRN** [comment]
Hey @AppinessVashum, I am also experiencing the same crash... Have you found a way to fix it yet?

**Comment by AppinessVashum** [comment]
I haven't found the fix.

**Comment by MagdyZamel** [comment]
you can try this in 
containerView.isUserInteractionEnabled = false
