### ISSUE TITLE
modalPresentationStyle should be .FullScreen

### ISSUE THREAD

**Issue by frogcjn** [xxxAIRINxxx/MusicPlayerTransition#3]
Since there is no custom UIPresentationController, then the ModalViewController's modalPresentationStyle should be .FullScreen.

There are two different level of custom presentation.
1. custom animator only
   https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/CustomizingtheTransitionAnimations.html#//apple_ref/doc/uid/TP40007457-CH16-SW1
2. custom UIPresentationController, which manage all staff about presentation (including the dimming View) https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/DefiningCustomPresentations.html#//apple_ref/doc/uid/TP40007457-CH25-SW1

since the musicPlayerTransition do not need custom UIPresentationController, the the ModalViewController's should be .FullScreen, and system will call viewWillAppear, viewDidAppear, viewDidDisappear, viewWillDisappear automatically.

**Comment by xxxAIRINxxx** [comment]
Hi.
Sorry for the delay in my response...
You're right. 
I resolved it.

17548ea0059e110b9a53c866f7bd97c508331980

Thanks!
