### ISSUE TITLE
Trouble when ModalView has a clear background

### ISSUE THREAD

**Issue by hsavit1** [xxxAIRINxxx/MusicPlayerTransition#4]
When the presenting modalview has a clear background, i get a black screen because self!.view.removeFromSuperview() gets called

I cant seem to figure a way around this...

**Comment by hsavit1** [comment]
ive tried 

`self.modalVC.modalPresentationStyle = .OverFullScreen` but that doesn't seem to be enough

**Comment by xxxAIRINxxx** [comment]
Please try this

`self.modalVC.modalPresentationStyle = .Custom`

In that case, please look here.
(should call view controller appearance functions) 

#2

**Comment by hsavit1** [comment]
That still doesn't solve the problem for me

I'm trying to present a modal view controller with a UIVibracyEffect / UIBlurView background over the current view

Another issue that I'm having is that when the modal view gets presented, then dragged down a bit (starting to dismiss), then dragged back up and returned to full screen (cancelled dismiss) the background view controller disappears

**Comment by mehdi-shiba** [comment]
I am having the exact same problem:
Adding UIBlurView to the modalView only works during the transition. As soon as the transition ends, I get a black background instead of a blurred view. Any idea of where to look at the fix this?

**Comment by xxxAIRINxxx** [comment]
Hmm ...
I will try to reproduce the problem.

**Comment by xxxAIRINxxx** [comment]
I fixed it.
699cd6249db17ca18007fb166885dcbaf1a6643b

@mehdi-shiba Thanks!
